// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieQuotes.Infrastructure;

#nullable disable

namespace MovieQuotes.Infrastructure.Migrations
{
    [DbContext(typeof(MovieQuotesDbContext))]
    [Migration("20260316221214_SpacedSpacedRepetion")]
    partial class SpacedSpacedRepetion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MovieQuotes.Domain.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("BaseFolderDir")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("CoverFilePath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(700)
                        .HasColumnType("varchar(700)");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("IMDBId")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("NameId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("VideoFilePath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Year")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasAlternateKey("FolderName");

                    b.HasAlternateKey("NameId");

                    b.HasAlternateKey("Title");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("MovieQuotes.Domain.Models.PhraseWords", b =>
                {
                    b.Property<int>("PhraseId")
                        .HasColumnType("int");

                    b.Property<int>("WordId")
                        .HasColumnType("int");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.HasKey("PhraseId", "WordId", "Index");

                    b.HasIndex("WordId");

                    b.HasIndex("PhraseId", "WordId", "Index");

                    b.ToTable("PhraseWords");
                });

            modelBuilder.Entity("MovieQuotes.Domain.Models.StudyPhrase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ArContentTranslation")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("ArPhraseTranslation")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Content")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Origin")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("PhraseId")
                        .HasColumnType("int");

                    b.Property<string>("StudyType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Translation")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("PhraseId");

                    b.ToTable("StudyPhrases");
                });

            modelBuilder.Entity("MovieQuotes.Domain.Models.StudyPhraseProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("EaseFactor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double")
                        .HasDefaultValue(2.5);

                    b.Property<int>("IntervalDays")
                        .HasColumnType("int");

                    b.Property<int>("LapseCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastReviewed")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NextReviewDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Repetition")
                        .HasColumnType("int");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<int>("StudyPhraseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudyPhraseId")
                        .IsUnique();

                    b.ToTable("StudyPhraseProgress");
                });

            modelBuilder.Entity("MovieQuotes.Domain.Models.SubtitlePhrase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time(6)");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time(6)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("varchar(700)");

                    b.Property<string>("VideoClipPath")
                        .HasMaxLength(700)
                        .HasColumnType("varchar(700)");

                    b.HasKey("Id");

                    b.HasAlternateKey("MovieId", "Sequence");

                    b.HasIndex("Text");

                    b.ToTable("SubtitlePhrases");
                });

            modelBuilder.Entity("MovieQuotes.Domain.Models.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Text");

                    b.HasIndex("Text");

                    b.ToTable("Word");
                });

            modelBuilder.Entity("MovieQuotes.Domain.Models.PhraseWords", b =>
                {
                    b.HasOne("MovieQuotes.Domain.Models.SubtitlePhrase", "Phrase")
                        .WithMany("PhraseWords")
                        .HasForeignKey("PhraseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieQuotes.Domain.Models.Word", "Word")
                        .WithMany("Phrases")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phrase");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("MovieQuotes.Domain.Models.StudyPhrase", b =>
                {
                    b.HasOne("MovieQuotes.Domain.Models.SubtitlePhrase", "Phrase")
                        .WithMany()
                        .HasForeignKey("PhraseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phrase");
                });

            modelBuilder.Entity("MovieQuotes.Domain.Models.StudyPhraseProgress", b =>
                {
                    b.HasOne("MovieQuotes.Domain.Models.StudyPhrase", "StudyPhrase")
                        .WithOne("Progress")
                        .HasForeignKey("MovieQuotes.Domain.Models.StudyPhraseProgress", "StudyPhraseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudyPhrase");
                });

            modelBuilder.Entity("MovieQuotes.Domain.Models.SubtitlePhrase", b =>
                {
                    b.HasOne("MovieQuotes.Domain.Models.Movie", "Movie")
                        .WithMany("Subtitles")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieQuotes.Domain.Models.Movie", b =>
                {
                    b.Navigation("Subtitles");
                });

            modelBuilder.Entity("MovieQuotes.Domain.Models.StudyPhrase", b =>
                {
                    b.Navigation("Progress");
                });

            modelBuilder.Entity("MovieQuotes.Domain.Models.SubtitlePhrase", b =>
                {
                    b.Navigation("PhraseWords");
                });

            modelBuilder.Entity("MovieQuotes.Domain.Models.Word", b =>
                {
                    b.Navigation("Phrases");
                });
#pragma warning restore 612, 618
        }
    }
}
