<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire" Version="1.8.24" />
    <PackageReference Include="Hangfire.MySqlStorage" Version="2.0.3" />
    <PackageReference Include="MediatR" Version="13.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MovieQuotes.Domain\MovieQuotes.Domain.csproj" />
    <ProjectReference Include="..\MovieQuotes.Infrastructure\MovieQuotes.Infrastructure.csproj" />
  </ItemGroup>

   

</Project>
